'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const worlds=[
 {name:'Mediterranean Lagoon',image:'turtle',alt:'A sea turtle moving above a sunlit marine habitat',tag:'A familiar sea. A new perspective.',volume:'850,000 L',temp:'18–22 °C',time:'45 min',copy:'Begin close to home. Follow the changing light through coastal habitats and meet the animals that share the Mediterranean with us. A slower look reveals a world usually hidden beneath the waves.'},
 {name:'Coral Reef',image:'reef',alt:'A clownfish resting among purple anemone tentacles',tag:'Life in extraordinary colour.',volume:'420,000 L',temp:'26 °C',time:'30 min',copy:'Small fish. Intricate shelters. Unexpected neighbours. Discover how the reef brings a remarkable variety of marine life together, and take time to notice the tiny details that keep it moving.'},
 {name:'The Tunnel',image:'tunnel',alt:'A glass aquarium tunnel surrounded by swimming fish',tag:'Forty-two metres of pure wonder.',volume:'3,400,000 L',temp:'18 °C',time:'25 min',copy:'Watch the ocean move above and around you. The route passes beneath the main tank through a 42-metre glass tunnel, giving you a completely different perspective on life underwater.'},
 {name:'Kelp Forest',image:'kelp',alt:'Brown kelp fronds floating in a green underwater forest',tag:'An underwater forest in motion.',volume:'610,000 L',temp:'13 °C',time:'20 min',copy:'Step into the gentle rhythm of a living underwater forest. Follow the fronds, watch for movement between the leaves and discover a habitat shaped by cold, nutrient-rich water.'},
 {name:'Bioluminescent Abyss',image:'hero',alt:'An artistic deep-sea scene with a glowing turquoise jellyfish',tag:'When the darkness comes alive.',volume:'240,000 L',temp:'6 °C',time:'25 min',copy:'As the route grows darker, another kind of light takes over. Explore the surprising ways deep-sea life uses light, and let the unhurried movement of the jellyfish bring your visit to a quieter pace.'},
 {name:'Penguin Island',image:'penguins',alt:'A colony of African penguins between coastal rocks',tag:'A different kind of ocean life.',volume:'300,000 L',temp:'5 °C',time:'15 min',copy:'Finish your descent with a fresh perspective on the water’s edge. Watch the colony gather, move and explore, and discover the connection between life on land and life at sea.'}
];
const experiences=[
 {name:'Shark dive',group:'adults',label:'Adults · 18+',image:'shark',alt:'A hammerhead shark swimming through clear aquarium water',price:180,duration:'90 minutes',copy:'Trade the view from the glass for an encounter inside the main tank, guided by two instructors.',detail:'This concept experience includes an introduction with the instructors, equipment preparation and forty minutes in an open cage in the main tank. For adults aged 18 and over.'},
 {name:'Night at the aquarium',group:'families',label:'Families · Ages 6–12',image:'tunnel',alt:'An underwater tunnel ready for an after-hours aquarium visit',price:95,duration:'14 hours',copy:'Fall asleep beneath the tunnel. Wake up with a story that lasts much longer than a day out.',detail:'An overnight aquarium experience for children aged 6–12 with an accompanying adult. Discover the route after hours, settle into sleeping bags beneath the tunnel and see the aquarium in a different light.'},
 {name:'Behind the scenes',group:'adults',label:'Curious minds · Ages 10+',image:'diving',alt:'A diver observing a school of fish underwater',price:25,duration:'60 minutes',copy:'Meet the work behind the wonder, from animal care to the systems that keep the water moving.',detail:'A guided look at the technical side of the aquarium: food preparation, quarantine and water filtration. The visual is illustrative marine photography, not a photograph of an ABYSSA facility.'},
 {name:'Feeding time',group:'families',label:'All ages',image:'turtle',alt:'A sea turtle swimming close to a reef habitat',price:12,duration:'30 minutes',copy:'See feeding time through the eyes of the biologist who prepares it. Bring every question.',detail:'Join a biologist for a narrated feeding session at the main tank. The demonstration explores the animals’ diets and the thinking behind their daily care.'},
 {name:'A fragile Mediterranean',group:'adults',label:'All ages',image:'kelp',alt:'Coastal seaweed illustrating a marine habitat',price:18,duration:'75 minutes',copy:'Follow a biologist through the route and discover the relationships that keep a sea alive.',detail:'A guided interpretation of the aquarium route, focused on Mediterranean habitats and the ways marine life depends on a healthy ecosystem.'},
 {name:'Small world. Big discoveries.',group:'schools',label:'School groups',image:'reef',alt:'A close view of an anemone and its resident clownfish',price:8,duration:'90 minutes',copy:'A hands-on introduction to marine life, with a closer look at the smallest inhabitants of the sea.',detail:'The original school-lab concept introduces plankton through microscopy. This educational session is designed for primary and secondary school groups. The price is a sample rate per pupil; real group bookings are not available.'}
];
const pad=n=>String(n+1).padStart(2,'0');
$('#world-grid').innerHTML=worlds.map((w,i)=>`<button class="world-card reveal" data-world="${i}" aria-label="Explore ${w.name}"><img src="assets/${w.image}-small.webp" width="720" height="480" loading="lazy" alt="${w.alt}"><span class="world-number">WORLD / ${pad(i)}</span><span class="world-card-content"><h3>${w.name}</h3><small>${w.tag}</small><span class="world-arrow" aria-hidden="true">↗</span></span></button>`).join('');
$('#experience-grid').innerHTML=experiences.map((e,i)=>`<article class="experience-card reveal" data-group="${e.group}"><div class="experience-image"><img src="assets/${e.image}-small.webp" width="720" height="480" loading="lazy" alt="${e.alt}"><span class="experience-badge">${e.label}</span></div><h3>${e.name}</h3><p>${e.copy}</p><div class="experience-meta"><span>${e.duration}</span><span>Guided experience</span></div><div class="experience-bottom"><span>From €${e.price}<small> / person</small></span><button class="text-link" data-experience="${i}">Discover more ↗</button></div></article>`).join('');
let selectedWorld=0;
$('.model-choice').innerHTML=worlds.map((w,i)=>`<button data-model="${i}" class="${i===0?'active':''}" aria-label="Show ${w.name} in the model" aria-pressed="${i===0}">${pad(i)}</button>`).join('');
const detail=$('#detail-dialog'),booking=$('#booking-dialog');
let lastTrigger=null;
function openDialog(d,trigger){lastTrigger=trigger||document.activeElement;d.showModal();document.body.classList.add('modal-open');d.scrollTop=0;}
function closeDialog(d){d.close();}
$$('dialog').forEach(d=>{d.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastTrigger?.focus();});d.addEventListener('click',ev=>{if(ev.target===d){const r=d.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)d.close();}});});
function showWorld(i,trigger){const w=worlds[i];$('#detail-content').innerHTML=`<img class="detail-photo" src="assets/${w.image}.webp" alt="${w.alt}" width="1440" height="960"><div class="detail-body"><p class="eyebrow">THE JOURNEY / WORLD ${pad(i)}</p><h2 id="detail-title">${w.name}</h2><p>${w.copy}</p><div class="detail-facts"><div><strong>${w.volume}</strong><span>Exhibit volume</span></div><div><strong>${w.temp}</strong><span>Water temperature</span></div><div><strong>${w.time}</strong><span>Suggested time</span></div></div><button class="button" data-book>Include it in your visit ↗</button><p class="fine-print">Exhibition specifications retained from the original design concept. Photography is illustrative.</p></div>`;openDialog(detail,trigger);}
function showExperience(i,trigger){const e=experiences[i];$('#detail-content').innerHTML=`<img class="detail-photo" src="assets/${e.image}.webp" width="1440" height="960" alt="${e.alt}"><div class="detail-body"><p class="eyebrow">BEYOND THE GLASS / ${e.label}</p><h2 id="detail-title">${e.name}</h2><p>${e.detail}</p><div class="detail-facts"><div><strong>${e.duration}</strong><span>Experience duration</span></div><div><strong>€${e.price}</strong><span>Sample price per person</span></div></div><button class="button" data-add-experience="${i}">Add to my visit ↗</button><p class="fine-print">An interactive concept, with no live bookings or payments.</p></div>`;openDialog(detail,trigger);}
const prices=[{name:'Adult',note:'Ages 13 and over',price:28},{name:'Reduced',note:'Students and visitors aged 65+',price:22},{name:'Child',note:'Ages 3–12 · under 3 free',price:16},{name:'Family',note:'2 adults + 2 children',price:78}];
let quantities=[1,0,0,0];const chosenExperiences=new Set();
const extraOptions=[{name:'Audio guide',note:'English, Italian, French and German',price:5,perPerson:true},{name:'Abyss VR experience',note:'A twelve-minute journey into the deep',price:9,perPerson:true},{name:'Reserved parking',note:'One space for the day',price:6,perPerson:false}];
const chosenExtras=new Set();
$('#ticket-options').innerHTML=prices.map((t,i)=>`<div class="ticket-row"><div><h4>${t.name} <strong>€${t.price}</strong></h4><small>${t.note}</small></div><div class="counter"><button type="button" data-count="${i}" data-delta="-1" aria-label="Remove one ${t.name.toLowerCase()} ticket">−</button><output id="quantity-${i}" aria-label="${t.name} tickets">${quantities[i]}</output><button type="button" data-count="${i}" data-delta="1" aria-label="Add one ${t.name.toLowerCase()} ticket">+</button></div></div>`).join('');
$('#booking-extras').innerHTML=extraOptions.map((e,i)=>`<label class="extra-row"><input type="checkbox" data-extra="${i}"><span>${e.name}<small>${e.note}${e.perPerson?' · per visitor':' · per booking'}</small></span><strong>€${e.price}</strong></label>`).join('');
const localDate=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};
const dateInput=$('#visit-date');dateInput.min=localDate();dateInput.value=localDate();
function bookingLines(){const people=quantities.reduce((sum,q,i)=>sum+q*(i===3?4:1),0);let total=0,rows=[];quantities.forEach((q,i)=>{if(q){const value=q*prices[i].price;total+=value;rows.push(`<div class="summary-row"><span>${q} × ${prices[i].name}</span><span>€${value}</span></div>`);}});chosenExtras.forEach(i=>{const e=extraOptions[i],value=e.price*(e.perPerson?people:1);total+=value;rows.push(`<div class="summary-row"><span>${e.name}${e.perPerson?' × '+people:''}</span><span>€${value}</span></div>`);});chosenExperiences.forEach(i=>{const e=experiences[i];total+=e.price;rows.push(`<div class="summary-row"><span>${e.name} × 1<br><button type="button" class="text-link" data-remove-experience="${i}">Remove experience</button></span><span>€${e.price}</span></div>`);});return {people,total,rows};}
function updateBooking(){$('#booking-error').textContent='';const {people,total,rows}=bookingLines();let date='Choose a date';if(/^\d{4}-\d{2}-\d{2}$/.test(dateInput.value)){const d=new Date(dateInput.value+'T12:00:00');if(!Number.isNaN(d.getTime()))date=d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'long'});}$('#summary-lines').innerHTML=`<p class="summary-date">${date} · ${$('#visit-time').value}<br>${people} ${people===1?'visitor':'visitors'}</p>`+rows.join('');$('#booking-total').textContent='€'+total;quantities.forEach((q,i)=>{$('#quantity-'+i).value=q;$(`[data-count="${i}"][data-delta="-1"]`).disabled=q===0;$(`[data-count="${i}"][data-delta="1"]`).disabled=q>=12;});}
function startBooking(trigger){if(detail.open)detail.close();$('#booking-form').hidden=false;$('#booking-confirmation').hidden=true;dateInput.min=localDate();if(dateInput.value<dateInput.min)dateInput.value=dateInput.min;$('#booking-error').textContent='';updateBooking();openDialog(booking,trigger);}
const infoContent={
 getting:{title:'Find your way to the water.',image:'tunnel',body:'<p>The ABYSSA concept is set at Molo San Vincenzo in the Port of Naples. These visitor details are retained from the original project and are illustrative.</p><ul><li><strong>Metro:</strong> Municipio, lines 1 and 6; allow around ten minutes on foot.</li><li><strong>Train:</strong> from Napoli Centrale, take Metro Line 1 towards Municipio.</li><li><strong>Ferry:</strong> the route begins near Molo Beverello.</li></ul><p>No real venue or visitor service is operated through this website.</p>'},
 access:{title:'Wonder should be for everyone.',image:'tunnel',body:'<p>Accessibility is part of the visitor experience imagined for ABYSSA.</p><ul><li>Step-free routes for wheelchair users and visitors with pushchairs.</li><li>Wheelchair loans and sensory bags at the entrance.</li><li>A quieter visiting hour on Tuesdays at 09:30.</li><li>Tactile maps and sign-language tours by arrangement.</li></ul><p>These are concept features from the original brief, not verified services at an operating venue.</p>'},
 project:{title:'A concept with real craft.',image:'hero',body:'<p>ABYSSA is an independent aquarium website concept, created as a portfolio demonstration of visual design, storytelling and interactive web development. It is not a real aquarium or a live ticketing service.</p><p>The redesign combines an original panoramic hero interpretation, licensed marine photography, an interactive 3D exhibition study and a working visit-planner demonstration.</p><p>Prices, exhibit specifications and schedules are sample content retained or adapted from the original concept. No visitor reviews, client endorsements or commercial results have been invented.</p><a class="button" href="https://www.upwork.com/freelancers/~0153439c4f13c2671f" target="_blank" rel="noopener noreferrer">Discuss your project on Upwork ↗</a>'},
 privacy:{title:'A quieter kind of website.',image:'kelp',body:'<p>This standalone portfolio demo has no analytics scripts, advertising trackers, account system or payment processor. The visit planner operates in memory in your browser and does not submit your information.</p><p>The hosting provider may keep standard access logs. External links, including Upwork and photography credits, have their own privacy policies.</p>'},
 credits:{title:'The world behind the images.',image:'turtle',body:'<p>Photographs are illustrative marine images, not photographs of a real ABYSSA facility. They are used under the <a href="https://unsplash.com/license" target="_blank" rel="noopener noreferrer">Unsplash License</a>.</p><ul><li><a href="https://unsplash.com/photos/DcweRpj62Ds" target="_blank" rel="noopener noreferrer">Aquarium tunnel — Zachary Spears</a></li><li><a href="https://unsplash.com/photos/bpdoFNQP2iw" target="_blank" rel="noopener noreferrer">Turtle and reef — NEOM</a></li><li><a href="https://unsplash.com/photos/HDVmdzQxAds" target="_blank" rel="noopener noreferrer">Clownfish — David Clode</a></li><li><a href="https://unsplash.com/photos/7i5HMCGupVw" target="_blank" rel="noopener noreferrer">Divers — Sebastian Pena Lambarri</a></li><li><a href="https://unsplash.com/photos/Ugap_KY-OF8" target="_blank" rel="noopener noreferrer">Kelp — Daniel Salcius</a></li><li><a href="https://unsplash.com/photos/Qv8ozq0Go9o" target="_blank" rel="noopener noreferrer">Penguins — Kylli Kittus</a></li><li><a href="https://unsplash.com/photos/a-close-up-of-a-shark-in-an-aquarium-OadqT_zjXqM" target="_blank" rel="noopener noreferrer">Hammerhead shark — Robin Teng</a></li></ul><p>The animated hero is an original real-time 3D jellyfish built from geometry and shaders. The panoramic fallback and abyss artwork are AI-generated interpretations inspired by the user-provided reference. The reference video is not distributed with this website.</p>'}
};
function showInfo(key,trigger){const i=infoContent[key];if(!i)return;$('#detail-content').innerHTML=`<img class="detail-photo" src="assets/${i.image}.webp" alt="${worlds.find(w=>w.image===i.image)?.alt||'A sea turtle swimming above coral'}" width="1440" height="960"><div class="detail-body"><p class="eyebrow">ABYSSA / INFORMATION</p><h2 id="detail-title">${i.title}</h2>${i.body}</div>`;openDialog(detail,trigger);}
function dashboard(period='7'){const multiplier=period==='30'?4:period==='365'?48:1;$('#detail-content').innerHTML=`<img class="detail-photo" style="height:150px" src="assets/tunnel.webp" alt="Aquarium tunnel" width="1440" height="960"><div class="detail-body"><p class="eyebrow">OPERATIONS / SIMULATED DATA</p><h2 id="detail-title">A clearer view.</h2><p>An operations dashboard concept. All figures below are sample data, not live readings or real business results.</p><div class="filter-row">${[['7','7 days'],['30','30 days'],['365','12 months']].map(([v,t])=>`<button data-period="${v}" class="filter ${period===v?'active':''}" aria-pressed="${period===v}">${t}</button>`).join('')}</div><div class="dashboard-grid"><div class="metric"><span>Visitors</span><strong>${(20860*multiplier).toLocaleString('en-GB')}</strong></div><div class="metric"><span>Ticket revenue</span><strong>€${(512400*multiplier).toLocaleString('en-GB')}</strong></div><div class="metric"><span>Slot occupancy</span><strong>78%</strong></div><div class="metric"><span>Online sales</span><strong>64%</strong></div></div><h3>Typical week at a glance</h3><div class="chart" role="img" aria-label="Sample attendance: Monday 2410, Tuesday 1980, Wednesday 2640, Thursday 2310, Friday 3120, Saturday 4380, Sunday 4020 visitors">${[2410,1980,2640,2310,3120,4380,4020].map((v,i)=>`<div style="height:${v/4380*100}%"><b>${v}</b><span>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</span></div>`).join('')}</div><h3>Exhibit systems</h3><ul class="tank-status">${worlds.map((w,i)=>`<li>${w.name}<span class="${i===3||i===5?'warning':''}">${i===3?'Turbidity alert':i===5?'Pump maintenance':'Nominal'}</span></li>`).join('')}</ul></div>`;if(!detail.open)openDialog(detail);}
document.addEventListener('click',ev=>{const b=ev.target.closest('button,a');if(!b)return;
 if(b.hasAttribute('data-world'))showWorld(+b.dataset.world,b);
 if(b.hasAttribute('data-experience'))showExperience(+b.dataset.experience,b);
 if(b.hasAttribute('data-book'))startBooking(b);
 if(b.hasAttribute('data-close'))closeDialog(b.closest('dialog'));
 if(b.hasAttribute('data-info'))showInfo(b.dataset.info,b);
 if(b.hasAttribute('data-dashboard'))dashboard();
 if(b.hasAttribute('data-period'))dashboard(b.dataset.period);
 if(b.hasAttribute('data-add-experience')){chosenExperiences.add(+b.dataset.addExperience);startBooking(b);}
 if(b.hasAttribute('data-remove-experience')){chosenExperiences.delete(+b.dataset.removeExperience);updateBooking();}
 if(b.hasAttribute('data-count')){const i=+b.dataset.count;quantities[i]=Math.max(0,Math.min(12,quantities[i]+ +b.dataset.delta));updateBooking();}
 if(b.hasAttribute('data-model')){selectedWorld=+b.dataset.model;$$('[data-model]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});$('#model-name').textContent=pad(selectedWorld)+' — '+worlds[selectedWorld].name;document.dispatchEvent(new CustomEvent('abyssa-world',{detail:selectedWorld}));}
 if(b.hasAttribute('data-filter')){$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});$$('.experience-card').forEach(c=>{c.hidden=b.dataset.filter!=='all'&&c.dataset.group!==b.dataset.filter;if(!c.hidden)c.classList.add('visible');});}
 if(b.closest('#main-nav')){$('#main-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').setAttribute('aria-label','Open menu');}
});
$('#model-details').addEventListener('click',ev=>showWorld(selectedWorld,ev.currentTarget));
$('.menu-toggle').addEventListener('click',()=>{const open=$('#main-nav').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String(open));$('.menu-toggle').setAttribute('aria-label',open?'Close menu':'Open menu');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#main-nav').classList.contains('open')){$('#main-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').setAttribute('aria-label','Open menu');$('.menu-toggle').focus();}});
$('#booking-extras').addEventListener('change',e=>{const i=+e.target.dataset.extra;e.target.checked?chosenExtras.add(i):chosenExtras.delete(i);updateBooking();});
dateInput.addEventListener('change',updateBooking);$('#visit-time').addEventListener('change',updateBooking);
$('#booking-form').addEventListener('submit',e=>{e.preventDefault();const s=bookingLines();if(!s.people){$('#booking-error').textContent='Add at least one ticket to preview your visit.';return;}if(dateInput.value<localDate()){$('#booking-error').textContent='Choose today or a future date.';return;}$('#booking-form').hidden=true;$('#booking-confirmation').hidden=false;$('#booking-confirmation').innerHTML=`<div class="confirmation" tabindex="-1"><p class="eyebrow">YOUR VISIT, AT A GLANCE</p><h3>Wonder looks good on you.</h3><p>Your sample itinerary is ready for ${dateInput.value} at ${$('#visit-time').value}, for ${s.people} ${s.people===1?'visitor':'visitors'}.</p><div class="detail-facts"><div><strong>Six worlds</strong><span>Included in your route</span></div><div><strong>€${s.total}</strong><span>Estimated sample total</span></div></div><p>This is a preview only. No tickets have been reserved and no payment has been taken.</p><button class="button" type="button" id="edit-visit">Edit my visit ↗</button></div>`;$('#edit-visit').addEventListener('click',()=>{$('#booking-confirmation').hidden=true;$('#booking-form').hidden=false;dateInput.focus();});$('.confirmation').focus();booking.scrollTop=0;});
updateBooking();
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches;
import('./hero-3d.js').then(m=>m.initHero($('#hero-webgl'),paused||reduced.matches)).catch(()=>{});
function motionState(){document.body.classList.toggle('motion-paused',paused||reduced.matches);const stop=paused||reduced.matches;$('.motion-toggle').textContent=stop?'Motion paused ▷':'Pause motion Ⅱ';$('.motion-toggle').setAttribute('aria-pressed',String(stop));document.dispatchEvent(new CustomEvent('abyssa-motion',{detail:stop}));}
$('.motion-toggle').addEventListener('click',()=>{if(reduced.matches){$('.motion-toggle').textContent='Reduced motion enabled';return;}paused=!paused;motionState();});reduced.addEventListener('change',()=>{paused=reduced.matches;motionState();});motionState();
if(!reduced.matches){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});$$('.reveal').forEach(e=>observer.observe(e));}
const stage=$('#model-stage');const modelObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){modelObserver.disconnect();import('./scene.js').then(m=>m.initScene(stage,paused||reduced.matches)).catch(()=>{stage.classList.add('fallback');$('.model-hint').textContent='Use the numbered buttons to explore each environment.';});}},{rootMargin:'350px'});modelObserver.observe(stage);
